language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.tests.txt"
script:
    # Run tests with coverage
  - 'coverage run --source="."  --omit="*test*" setup.py test'
  - "coverage report -m"
    # install sshm
  - "python setup.py install"
    # sshm should be available on console
  - "sshm --help"
    # output the version into the console
  - "sshm --version"
    # sshm should be avaliable in the python console
  - "python -c 'from sshm.lib import sshm'"
