language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.tests.txt"
script:
    # Run tests
  - "python setup.py test"
    # install sshm
  - "python setup.py install"
    # sshm should be available on console
  - "sshm --help"
    # sshm should be avaliable in the python console
  - "python -c 'from sshm import sshm'"
