language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
script:
    # Run tests
  - "python setup.py test"
    # install sshm
  - "python setup.py install"
